<a href="https://colab.research.google.com/github/MihirDesh/Neural-Network-from-Scratch/blob/main/NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import math
softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]
target_class = 0
loss = -(math.log(softmax_output[0]) * target_output[0] + math.log(softmax_output[1]) * target_output[1] + math.log(softmax_output[2]) * target_output[2])
loss

0.35667494393873245

In [2]:
pip install nnfs

In [6]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()


class Layer_dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

class Activation_Softmax:
  def forward(self, inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
    probabilities = exp_values / np.sum(exp_values, axis = 1, keepdims = True)
    self.output = probabilities

X, y = spiral_data(samples = 100, classes = 3)

dense1 = Layer_dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [7]:
import numpy as np
np.random.seed(0)


X = [[1, 2, 3, 2.5],
      [2.0, 5.0, -1.0, 2.0],
      [-1.5, 2.7, 3.3, -0.8]]

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

for i in inputs:
  if i > 0:
    output.append(i)
  elif i <= 0:
    output.append(0)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [8]:
import numpy as np

inputs = [1, 2, 3, 2.5]

weights = [0.2, 0.8, -0.5, 1.0]

bias = 2

output = np.dot(inputs, weights) + bias

AttributeError: ignored

In [10]:

layer_outputs = []
for neuron_weights, neuron_bias in zip(weights, biases):
  neuron_output = 0
  for n_input, weight in zip(inputs, neuron_weights):
    neuron_output += n_input * weight
  neuron_output += neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)


TypeError: ignored